name: ci

on:
  push:
    branches:
      - develop
      - main
    tags:
      - "*-RELEASE"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: poonnachitdevops/mg-app:develop-${{ github.sha }}

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: poonnachitdevops/mg-app:sut-${{ github.sha }}

      - name: Build and push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: poonnachitdevops/mg-app:production-${{ github.sha }}


  update-gitops:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:  
      - name: Update GitOps
        if: github.ref == 'refs/heads/develop'
        run: |
          git clone https://update-gitops:${{ secrets.PAT }}@github.com/Poonnachit/mg-nod-prod-manifest.git
          cd mg-nod-prod-manifest
          yq -i '.spec.template.spec.containers[0].image="poonnachitdevops/mg-app:develop-${{ github.sha }}"' develop/pedjeab/mg-cart/deployment.yaml
          git config --global user.email "poonnachit.devops@myorder.ai"
          git config --global user.name "Poonanchit"
          git commit -m "update image tag to mg-app to develop-${{ github.sha }}" develop/pedjeab/mg-cart/deployment.yaml --allow-empty
          git push origin main
      - name: Update GitOps
        if: github.ref == 'refs/heads/main'
        run: |
          git clone https://update-gitops:${{ secrets.PAT }}@github.com/Poonnachit/mg-nod-prod-manifest.git
          cd mg-nod-prod-manifest
          yq -i '.spec.template.spec.containers[0].image="poonnachitdevops/mg-app:sut-${{ github.sha }}"' sut/pedjeab/mg-cart/deployment.yaml
          git config --global user.email "poonnachit.devops@myorder.ai"
          git config --global user.name "Poonanchit"
          git commit -m "update image tag to mg-app to sut-${{ github.sha }}" sut/pedjeab/mg-cart/deployment.yaml --allow-empty
          git push origin main
      - name: Update GitOps
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git clone https://update-gitops:${{ secrets.PAT }}@github.com/Poonnachit/mg-nod-prod-manifest.git
          cd mg-nod-prod-manifest
          yq -i '.spec.template.spec.containers[0].image="poonnachitdevops/mg-app:production-${{ github.sha }}"' production/pedjeab/mg-cart/deployment.yaml
          git config --global user.email "poonnachit.devops@myorder.ai"
          git config --global user.name "Poonanchit"
          git commit -m "update image tag to mg-app to production-${{ github.sha }}" production/pedjeab/mg-cart/deployment.yaml --allow-empty
          git push origin main


        
