name: ci

on:
  push:
    branches:
      - develop
      - main
    tags:
      - "*-RELEASE"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: get-short-sha
        run: |
          echo ${{github.sha}} | cut -c 1-7 >> $GITHUB_OUTPUT

      - name: Build and push
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: docker.io/poonnachitdevops/mg-app:develop-${{steps.get-short-sha.outputs.id}}

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: docker.io/poonnachitdevops/mg-app:sut-${{steps.get-short-sha.outputs.id}}

      - name: Build and push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: docker.io/poonnachitdevops/mg-app:production-${{steps.get-short-sha.outputs.id}}


  update-gitops:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:  
      - name: Update GitOps
        if: github.ref == 'refs/heads/develop'
        run: |
          git clone https://update-gitops:${{ secrets.PAT }}@github.com/Poonnachit/mg-nod-prod-manifest.git
          cd mg-nod-prod-manifest
          yq -i '.spec.template.spec.containers[0].image="docker.io/poonnachitdevops/mg-app:develop-${{steps.get-short-sha.outputs.id}}"' develop/pedjeab/mg-cart/deployment.yaml
          git config --global user.email "poonnachit.devops@myorder.ai"
          git config --global user.name "Poonanchit"
          git commit -m "update image tag to mg-app to develop-${{steps.get-short-sha.outputs.id}}" develop/pedjeab/mg-cart/deployment.yaml --allow-empty
          git push origin main
      - name: Update GitOps
        if: github.ref == 'refs/heads/main'
        run: |
          git clone https://update-gitops:${{ secrets.PAT }}@github.com/Poonnachit/mg-nod-prod-manifest.git
          cd mg-nod-prod-manifest
          yq -i '.spec.template.spec.containers[0].image="docker.io/poonnachitdevops/mg-app:sut-${{steps.get-short-sha.outputs.id}}"' sut/pedjeab/mg-cart/deployment.yaml
          git config --global user.email "poonnachit.devops@myorder.ai"
          git config --global user.name "Poonanchit"
          git commit -m "update image tag to mg-app to sut-${{steps.get-short-sha.outputs.id}}" sut/pedjeab/mg-cart/deployment.yaml --allow-empty
          git push origin main
      - name: Update GitOps
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git clone https://update-gitops:${{ secrets.PAT }}@github.com/Poonnachit/mg-nod-prod-manifest.git
          cd mg-nod-prod-manifest
          yq -i '.spec.template.spec.containers[0].image="docker.io/poonnachitdevops/mg-app:production-${{steps.get-short-sha.outputs.id}}"' production/pedjeab/mg-cart/deployment.yaml
          git config --global user.email "poonnachit.devops@myorder.ai"
          git config --global user.name "Poonanchit"
          git commit -m "update image tag to mg-app to production-${{steps.get-short-sha.outputs.id}}" production/pedjeab/mg-cart/deployment.yaml --allow-empty
          git push origin main


        
