name: ci

on:
  push:
    branches:
      - develop
      - main
    tags:
      - "*-RELEASE"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: ${{ github.bash_ref == "develop" }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: poonnachitdevops/mg-app:develop-${{ github.sha }}

      - name: Build and push
        if: ${{ github.bash_ref == "main" }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: poonnachitdevops/mg-app:sut-${{ github.sha }}

      - name: Build and push
        if: ${{ github.ref_type == "tag" }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: poonnachitdevops/mg-app:release-${{ github.sha }}


  update-gitops:
    runs-on: ubuntu-latest
    steps:  
      - name: Update GitOps
        if: ${{ github.bash_ref == "main" }}
        run: |
          git clone https://update-gitops:${{ secrets.PAT }}@github.com/Poonnachit/mg-nod-prod-manifest.git
          cd mg-nod-prod-manifest
          yq -i '.spec.template.spec.containers[0].image="poonnachitdevops/mg-app:${{ github.sha }}"' develop/pedjeab/mg-cart/deployment.yaml
          git config --global user.email "poonnachit.devops@myorder.ai"
          git config --global user.name "Poonanchit"
          git commit -m "update image tag to ${{ github.sha }}" develop/pedjeab/mg-cart/deployment.yaml --allow-empty
          git push origin main


        
